### ISSUE TITLE
use entry_points to run from command line

### ISSUE THREAD

**Issue by mtamizi** [manmartinez/killer-queen#2]
@manmartinez here's the best way to run from the command line when you're executing a module:
https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/

**Comment by mtamizi** [comment]
Here's another guide if you were using Click: http://click.pocoo.org/6/setuptools/

**Comment by manmartinez** [comment]
:+1: Thanks for the pointers

**Comment by mtamizi** [comment]
No longer necessary becase of 42e8486e4074dbbe62503662112ec759b17f105d
